/**
 * Created by teklof on 30.1.15.
 */
var _ = require('lodash');
var util = require('util');
var ut = require('./utils');
var Promise = require('bluebird');
var debug = require('debug')('s4qs-rs:s3-to-rs');
var error = require('debug')('s4qs-rs:s3-to-rs:error');
error.log = console.error;
var LRU = require('lru-cache');
var mup = require('./manifest-uploader');
var Uploader = mup.Uploader;
var inspect = _.partialRight(util.inspect, {depth: 10});

/**
 * S3Copier polls SQS for S3 object creation events and uses COPY to copy the S3 object data to Redshift.
 *
 * Don't forget to provide credentials in copyParams.
 *
 * @param {Object} s3 Initialized AWS S3 service object
 * @param {Object} pg Postgres module
 * @param {Object} rs Initialized AWS Redshift service object
 * @param {String} copyParams.schema Schema name to use
 * @param {String|Function} copyParams.table String with name of table to COPY to, or a function that takes an
 * S3 URI and returns a table name
 * @param {Array} copyParams.args Array of strings to be given as parameterless arguments to COPY. For example
 * ['GZIP', 'TRUNCATECOLUMNS']
 * @param {Object} copyParams.withParams Object with parametrized COPY arguments. For example
 * {'TIMEFORMAT': 'auto', 'NULL': 'null'}
 * @param {Object} poller SQS poller
 * @param {Number} options.pollIntervalSeconds Interval between SQS polls
 * @param {String} options.connStr Connection string for Redshift
 * @param {String} options.tablePostfix Added to the end of the table name generated by
 * copyParams.table. Handy for having different tables based on NODE_ENV
 * @param {Number} options.clusterAvailCheckInterval Check cluster status at clusterAvailCheckInterval ms intervals.
 * If the cluster is not available, SQS polling and manifest uploading will be stopped.
 * @param {Object} options.manifestUploader Manifest uploader options. See ./manifest-uploader.js for details.
 *
 * @param {Object} options.timeSeries Time series table configuration
 * @param {Number} options.timeSeries.period Time series table period in seconds. I.e. a value of 3600 would mean
 * a new time series table is created per every hour
 * @param {Number} options.timeSeries.maxTables Keep a maximum of maxTables time series tables. Oldest tables will be
 * deleted
 * @param {String} options.timeSeries.latestPostfix if this is set, use table name + this postfix to create a view
 * to the latest time series table
 * @param {Object} options.timeSeries.tableDef Time series table DDL etc.
 * @param {Array} options.timeSeries.tableDef.columns Array of column definitions like ["source int not null encode bytedict",
 * "campaign char(24) encode bytedict", "..."]
 * @param {Array} options.timeSeries.tableDef.tableAttrs Array of table attributes like ["DISTKEY(ID)", "SORTKEY(TS)"]
 * @constructor
 * @type {S3Copier}
 */
var S3Copier = exports.S3Copier = function S3Copier(poller, pg, s3, rs, copyParams, options) {
  if(!options) {
    throw new Error("Missing options");
  }

  if(!pg) {
    throw new Error("Missing PostgreSQL module");
  }

  if(!poller) {
    throw new Error("Missing poller");
  }

  if(!options.Redshift.connStr) {
    throw new Error("missing connection string");
  }

  if(!options.Redshift.params.ClusterIdentifier) {
    throw new Error("missing options.Redshift.params.ClusterIdentifier");
  }

  if(!options.manifestUploader) {
    throw new Error("missing manifest uploader options");
  }

  if(!rs) {
    throw new Error("Missing Redshift service");
  }

  if(!s3) {
    throw new Error("Missing S3 service")
  }

  if(!options.timeSeries) {
    throw new Error("Missing time series options");
  }

  var table = copyParams.table;
  if(!_.isString(table) && !_.isFunction(table)) {
    throw new Error("copyParams.table must be a string or function");
  }

  if(_.isString(table)) {
    this._tableNamer = _tableStrToNamer(table);
  } else {
    this._tableNamer = table;
  }

  this._pollIntervalS = options.pollIntervalSeconds || 60;

  this._availCheckInterval = options.Redshift.clusterAvailCheckInterval || -1;

  if(options.tablePostfix) {
    debug("Table postfix " + options.tablePostfix);
  }

  this._tablePostfix = options.tablePostfix || ""

  if(copyParams.args) {
    copyParams.args = [];
  }

  copyParams.args.push("MANIFEST");

  this._pg = pg;
  this._connStr = options.Redshift.connStr;
  this._copyTemplate = _copyParamsTempl(copyParams);
  this._poller = poller;
  this._rs = Promise.promisifyAll(rs);
  this.started = false;
  this._timeout = null; // used for SQS poller setTimeout obj
  this._availChk = null; // used for cluster availability check interval


  // if an _onMsg call is running, this'll contain an object with properties that'll be fulfilled when the messages
  // have been handled. Keys will be table names
  this._manifestsPending = {};
  var lruOpts = options.LRU || {max: 1000};
  this._seenMsgs = LRU(lruOpts);

  // since _tableNamer takes an S3 URI and turns it into a table name, we can use it as the manifest uploader's grouper
  this._uploader = new Uploader(s3, _.merge(options.manifestUploader, {grouper: this._tableNamer}));

  this._usingPg = function(fn) {
    return Promise.using(ut.getPgClient(this._pg, this._connStr), fn);
  }.bind(this);


  this._tsMgr = new TimeSeriesManager(this._usingPg, copyParams.schema, this._tablePostfix, options.timeSeries);

};

S3Copier.prototype._connAndCopy = function _connAndCopy(s3URI, table) {
  var self = this;
  debug("_connAndCopy " + s3URI);
  return this._usingPg(function (client) {
    var query = util.format(self._copyTemplate, table, s3URI);
    return client.queryAsync(query).return(s3URI);
  });

};

S3Copier.prototype._markSeen = function(msgs) {
  var self = this;
  _.each(msgs, function (msg) {
    self._seenMsgs.set(msg.MessageId, true);
  });
};

S3Copier.prototype._dedup = function(msgs) {
  var self = this;
  return new Promise(function (resolve) {
    var grouped = _.groupBy(msgs, function (msg) {
      return !!self._seenMsgs.get(msg.MessageId); // bang bang to coerce undefined into a bool
    }); // {true: [duplicates], false: [nondups]}

    var dups = grouped.true || [];
    var nonDups = grouped.false || [];

    if (dups.length > 0) {
      error("Found " + dups.length + " duplicate messages. Deleting");
      resolve(self._poller.deleteMsgs(dups)
        .catch(function (err) {
          error("Error deleting duplicates: " + err);
        })
        .tap(function() {
          debug("Duplicates deleted");
        })
        .return(nonDups))
      ;
    } else {
      resolve(nonDups);
    }

  });
};

S3Copier.prototype._delete = function(msgs) {
  debug("Deleting " + msgs.length + " messages");
  return this._poller.deleteMsgs(msgs)
    .catch(function (err) {
      error("Error deleting messages: " + err);
    })
    .tap(function () {
      debug("Messages deleted");
    });
};


S3Copier.prototype._onManifest = function _onManifest(manif) {
  debug("Handling manifest " + manif.manifestURI + " for base table " + manif.table);

  var promise = this._tsMgr.tsTableFor(manif.table).bind(this)
    .then(function (table) {
      debug("Copying " + manif.manifestURI + " to " + table);
      return this._connAndCopy(manif.manifestURI, table).bind(this)
        .then(function (uri) {
          debug("Manifest " + uri + " copied");
          return this._delete(manif.msgs).catch(function () {
            error("Couldn't delete messages for manifest " + manif.manifestURI)
          });
        })
        .catch(function (err) {
          error("Error copying manifest " + manif.manifestURI + ": " + err);
        })
        .then(function () {
          return manif.delete().catch(function (err) {
            error("Couldn't delete manifest " + manif.manifestURI + ": " + err);
          });
        })
        .return(manif);

    });

  if(this._manifestsPending[manif.table] && this._manifestsPending[manif.table].isPending()) {
    error("Already have a pending manifest upload for table " + manif.table + this._tablePostfix + "? Joining it anyhow");
    promise = Promise.join(promise, this._manifestsPending[manif.table]);
  }
  this._manifestsPending[manif.table] = promise;

};

S3Copier.prototype._onMsgs = function _onMsgs(msgs) {
  debug("Got " + msgs.length + " messages");
  var nextPoll = Date.now() + this._pollIntervalS * 1000
    , self = this
    ;

  return new Promise(function (resolve) {
    if(msgs.length == 0) {
      debug("No messages, scheduling new poll.");
      self._schedulePoll(nextPoll);
      resolve();
      return;
    }

    resolve(self._dedup(msgs).then(function(nondups) {
      self._uploader.addMessages(nondups);
      self._schedulePoll(nextPoll);
    }));
  });
};

S3Copier.prototype._schedulePoll = function(nextPoll) {
  if(!this.started) {
    return; // bail out early
  }
  var timeLeft = nextPoll - Date.now();

  if(timeLeft < 0) {
    timeLeft = 0;
  }
  debug("Seconds until next poll: " + timeLeft / 1000);
  this._timeout = setTimeout(this._poller.poll.bind(this._poller) , timeLeft);
};

/**
 * Stop the S3Copier. Returns a promise that'll be resolved once all underway COPYs are done.
 * @param {Boolean} checkAvail If true, don't stop the cluster availability checker.
 * @return {*}
 */
S3Copier.prototype.stop = function(checkAvail) {
  if(this.started) {
    // set this so that if _availHandler is waiting for its promise it won't try to start S3Copier again when it sees
    // it isn't started.
    this._reallyStop = !checkAvail;
    this.started = false;

    debug("Stopping. checkAvail " + checkAvail);

    this._uploader.removeAllListeners("manifest");
    this._poller.removeAllListeners("messages");
    this._uploader.stop();
    clearTimeout(this._timeout);

    if(!checkAvail) {
      clearInterval(this._availChk);
    }

    if(this._numPending() > 0) {
      debug(this._numPending() + " pending manifest(s). Waiting for them to finish");
      return Promise.props(this._manifestsPending);
    }
  }
  return Promise.resolve({});
};

S3Copier.prototype._numPending = function _numPending() {
  return _.reduce(this._manifestsPending, function (acc, val) {
    return acc + (val.isPending() ? 1 : 0);
  }, 0);
};

S3Copier.prototype._availHandler = function _availHandler() {
  debug("Checking cluster availability");
  this._isClusterAvail()
    .bind(this)
    .then(function (avail) {
      if (!avail) {
        if (this.started) {
          error("_availHandler: cluster went unavailable, stopping");
          return this.stop(true);
        } else {
          return Promise.resolve();
        }
      } else { // cluster available
        if (!this.started && !this._reallyStop) {
          error("_availHandler: cluster became available, starting");
          return this.start(true);
        } else {
          return Promise.resolve();
        }
      }
    });
};

S3Copier.prototype._isClusterAvail = function _isClusterAvail() {
  return this._rs.describeClustersAsync()
    .then(function (res) {
      if (res.Clusters.length != 1) {
        throw new Error("DescribeClusters got " + res.Clusters.length + " results: did you forget to set " +
                        "Redshift.params.ClusterIdentifier?");
      }

      debug("ClusterStatus " + res.Clusters[0].ClusterStatus);
      return res.Clusters[0].ClusterStatus === "available";
    })
    .catch(function (err) {
      error("_isClusterAvail got " + err + " when trying to check cluster availability");
      return false;
    });
};

/**
 * Starts the S3Copier
 * @param {Boolean} skipAvailCheck if skipAvailCheck is true, skip cluster availability check and just start.
 */
S3Copier.prototype.start = function start(skipAvailCheck) {
  if (!this.started) {
    return (skipAvailCheck ? Promise.resolve(true) : this._isClusterAvail())
      .bind(this)
      .then(function (avail) {
        if (avail) {
          debug("Cluster available, starting");
          this._uploader.start();
          this._poller.on('messages', this._onMsgs.bind(this));
          this._uploader.on('manifest', this._onManifest.bind(this));
          this._poller.poll();
          this.started = true;
        } else {
          error("Cluster unavailable, can't start yet");
          if (this._availCheckInterval < 0) {
            throw new Error("Cluster unavailable and no clusterAvailCheckInterval configured, bailing out");
          }
        }

        if (this._availCheckInterval > 0 && !this._availChk) {
          this._availChk = setInterval(this._availHandler.bind(this), this._availCheckInterval * 1000);
        }
      });
  }

  return Promise.resolve();
};

var _boolish = /^(true|on|false|off)$/i;
var _enc = /^encoding$/i;

var _copyParamsTempl = exports._copyParamsTempl = function _copyParamsTempl(copyParams) {

  copyParams.withParams = copyParams.withParams || {};
  copyParams.args = copyParams.args || [];

  var withp = _.reduce(_.pairs(copyParams.withParams), function (acc, pair) {
    var key = pair[0]
      , value = pair[1];
    if (!(_.isNumber(value) || value.toString().match(_boolish) || key.match(_enc))) {
      // we need quotes since value is not a number or boolean-ish, and the key isn't "encoding"
      value = "'" + value + "'";
    }
    acc.push(key + " " + value);

    return acc;

  }, []);

  return "COPY %s FROM '%s' " + copyParams.args.concat(withp).join(' ') + ";";
};

/**
 * Takes a string and turns it into a function that returns a table name for an S3 URI. If the string starts with
 * a '/' it's assumed to be a regex, and the returned function will use that regex to build table names. If the
 * string doesn't start with a '/', the function will always return whatever 'table' contains.
 * @param {String} table string given in config
 * @return {Function} Function that takes an S3 URI and returns a table name
 * @private
 */
exports._tableStrToNamer = _tableStrToNamer;

function _tableStrToNamer(table) {

  if(_.first(table) === '/') { // happily assume it's a regex
    var lastSlash = _.lastIndexOf(table, '/')
      , pattern = _.initial(_.rest(table)).join('').substring(0,lastSlash - 1)
      , flags = table.substring(lastSlash + 1)
      , re = new RegExp(pattern, flags);

    debug("Using pattern " + pattern + " based on " + table);
    return _.partial(_URIToTbl, re);
  } else {
    return function() {
      return table;
    };
  }
}

exports._URIToTbl = _URIToTbl;


function _URIToTbl(regex, uri) {
  var match = uri.match(regex);
  if(match && match[1]) {
    return match[1].split('.').join('_');
  } else {
    throw new Error("Can't turn '" + uri + "' into table name with regex " + regex);
  }
}

/**
 * Creates new time series tables if needed, creates views for the tables, and deletes old tables.
 * @param {Function} usingPgFn A function that takes another function which will be called with a promisified Postgres client
 * and returns a promise of a result
 * @param {String} postfix A table postfix to be added to the base name _before_ the time series postfix.
 * @constructor
 */
var TimeSeriesManager = exports.TimeSeriesManager = function TimeSeriesManager(usingPgFn, schema, postfix, options) {

  if(!_.isString(postfix)) {
    throw new Error("postfix not a string");
  }

  if(!schema) {
    throw new Error("missing schema");
  }

  if(!_.isFunction(usingPgFn)) {
    throw new Error("Postgres client getter not a function");
  }

  if(!options) {
    throw new Error("no options");
  }

  this._options = options;

  this._schema = schema;

  this._postfix = postfix;

  this._usingPg = usingPgFn;
};

function isDuplicate(error) {
  return error && error.code === "42P07";
}

/**
 * Finds time series tables for a base name and returns them in a promise of an array
 * @param name base name
 * @param limit optional LIMIT
 * @return {Promise} promise of array of table names, sorted oldest first
 * @private
 */
TimeSeriesManager.prototype._listTsTables = function(name, limit) {
  debug("_listTsTables " + name + " limit " + limit);
  // TODO: return an array of time series table names, with oldest ones first
  return this._usingPg(function (client) {
    var queryStr = "select tablename from pg_tables where schemaname = $1" +
                   " and tablename like $2 || '_ts_%' order by tablename asc"
      , params = [this._schema, name]
      ;

    if(limit) {
      queryStr += " limit $3";
      params.push(limit);
    }
    debug("_listTsTables query " + queryStr + " params " + inspect(params));
    return client.queryAsync(queryStr, params)
      .then(function (res) {
        return _.pluck(res.rows, "tablename");
      });
  }.bind(this));
};

TimeSeriesManager.prototype._dropTable = function(name) {
  debug("Dropping table " + name);
  return Promise.resolve(name);
/*  return this._usingPg(function(client) {
    debug("Dropped " + name);
    return client.queryAsync("drop table " + name).return(name;
  });*/
};

/**
 * Checks the amount of current time series tables for a base name, prunes them if necessary. Will return the names of
 * existing time series tables
 * @return {Promise} promise of array of existing time series tables
 * @private
 */
TimeSeriesManager.prototype._pruneTsTables = Promise.method(function(name) {
  return this._listTsTables(name).bind(this)
    .then(function(tables) {
      debug("_pruneTsTables found " + tables.length + " tables");
      var tsOpts = this._options[name];
      if(tables.length > tsOpts.maxTables) {
        var diff = tables.length - tsOpts.maxTables
          , toDelete = tables.slice(0, diff)
          , left = tables.slice(diff)
          ;
        debug("Dropping " + diff + "/" + tables.length + " time series table(s)");

        Promise.settle(_.map(toDelete, this._dropTable.bind(this))).then(function(drops) {
          _(toDelete).zip(drops).filter(drops, ut.send('isRejected'));

        });
        return left;
      }
      return tables;
    })
    ;
});

/**
 * Creates (if necessary) a time series table for a base name, and returns a promise of a time series table name.
 * @param {String} name base name for table. The "static" part of the table name, before any postfixes
 * @return {Promise} promise of time series table name
 * @private
 */
TimeSeriesManager.prototype.tsTableFor = Promise.method(function (name) {

  var tsOpts = this._options[name];

  if(!tsOpts) {
    throw new Error("Couldn't find time series configuration for table " + name);
  }

  var now = Date.now()
    , postf = this._postfix + "_ts_" + ((now - now % (tsOpts.period * 1000)) / 1000).toFixed(0);

  var tsTableName = this._schema + "." + name + postf
  // not using IF NOT EXISTS since we need to know whether a new table was created or not without
  // having to do extra queries
    , ddlStr = util.format("CREATE TABLE %s (%s) %s ", tsTableName, tsOpts.columns.join(',')
      , tsOpts.tableAttrs.join(' '));

  return this._usingPg(function (client) {
    return client.queryAsync(ddlStr)
  }).bind(this).return(tsTableName)
    .tap(function () {
      debug("Created new time series table " + tsTableName);

      // TODO: update view

      this._pruneTsTables(name)
        .tap(function(dels) {
          if(dels.length > 0) {
            debug("Deleted time series tables: " + dels.join(", "));
          }
        })
        .catch(function(err) {
          error("Error pruning time series tables: " + err.stack || err);
        })
    })
    .catch(isDuplicate, function () {
      debug("Time series table " + tsTableName + " already exists");
      return tsTableName;
    })
    ;
});
